Add AHI scenario, fix bug, update B tunning
NCAR/MPAS-Workflow pull request #133
Opened 2022-08-10 15:50 UTC by ibanos90

### Description
This PR adds a new scenario to run experiments with AHI observations, 120-km mesh and 3denvar. It also adds the option to use the prepbufr files under the prepnr folder in addition to prep48h on RDA. This is particularly important for the RealTime run since the new web link contains only 2 days of data. In addition, the original GFS analysis is removed automatically to save disk space. A bug found in the amsua_n15 YAML for the PrepQC filter is fixed and amsua_aqua is added to the list of observations to be converted to IODA (last 2 days available at https://ftpprd.ncep.noaa.gov/data/nccf/com/obsproc/prod/ and until 20201207 on RDA on Cheyenne). The B standard deviation file is updated in order to use the most recent tuned statistics.

### Issue closed
Closes https://github.com/NCAR/MPAS-Workflow/issues/132

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart

2022-08-10 16:12 UTC, jjguerrette commented
Please move the bug fix to a separate PR.  It's merging need not depend on reviewing this PR.

2022-08-10 17:59 UTC, ibanos90 commented
> Please move the bug fix to a separate PR. Its merging need not depend on reviewing this PR.

Thanks @jjguerrette. I opened a PR for the bug fix. Will update this too.

2022-08-12 17:44 UTC, jjguerrette commented on ExternalAnalysisToMPAS.csh
> +
This removes links to the ungrib file (`GFS:` prefix), which actually makes the dependency train more confusing for somebody looking through the directory structure of the experiment.  The original two files are stored in a different directory now.  For example, see the difference between `ExternalAnalysisDir` and `ExternalAnalysisDirOuter`.  So these two lines do not do what is expected.

2022-08-12 20:48 UTC, ibanos90 commented on ExternalAnalysisToMPAS.csh
> +
Thanks for catching this @jjguerrette. I am working on a fix for this.

2022-08-15 18:57 UTC, jjguerrette commented on ExternalAnalysisToMPAS.csh
> +rm -r ${ExternalAnalysisDir}/${externalanalyses__UngribPrefix}:${yy}-${mm}-${dd}_${hh}
Since the `ExternalAnalysisToMPAS` script may be executed for multiple meshes (e.g., 30km and 60km), it cannot safely remove those files.  See for example the 3dvar O30kmIE60km ColdStart test scenario.  If it is required that we remove those files to save space, we will need an extra `CleanExternalAnalyses` task.

2022-08-15 19:01 UTC, jjguerrette commented on GetObs.csh
> +             setenv THIS_FILE prepbufr.gdas.${ccyy}${mmdd}.t${hh}z.nr.48h
All these branching `if` statements designating default priority behaviors are fine for this PR, and probably sufficient for the next few months.  Eventually we may want to create a user-option to choose 48h data under the `observations` section of the YAML.  No need to do that now.

2022-08-16 17:00 UTC, jjguerrette commented on ExternalAnalysisToMPAS.csh
> +rm -r ${ExternalAnalysisDir}/${externalanalyses__UngribPrefix}:${yy}-${mm}-${dd}_${hh}
As we discussed, that can go on a separate PR.  Comment out for now, and then we can merge.

2022-08-16 17:19 UTC, ibanos90 commented on ExternalAnalysisToMPAS.csh
> +rm -r ${ExternalAnalysisDir}/${externalanalyses__UngribPrefix}:${yy}-${mm}-${dd}_${hh}
Ok, I will do that. Thanks @jjguerrette.

2022-08-19 18:52 UTC, jjguerrette requested changes
Looks good.  Just two small requests for changes.

2022-08-19 18:52 UTC, jjguerrette commented on config/jedi/ObsPlugs/variational/filtersWithBias/abi_g16.yaml
> +  obs filters:
This is identical to `config/jedi/ObsPlugs/variational/filters/abi_g16.yaml`.  Please use a link to that file instead of creating a new file.

2022-08-19 18:52 UTC, jjguerrette commented on config/jedi/ObsPlugs/variational/filtersWithBias/ahi_himawari8.yaml
> +  obs filters:
This is identical to `config/jedi/ObsPlugs/variational/filters/ahi_himawari8.yaml`.  Please use a link to that file instead of creating a new file.

2022-08-19 19:01 UTC, ibanos90 commented on config/jedi/ObsPlugs/variational/filtersWithBias/abi_g16.yaml
> +  obs filters:
That's right. I will change it. Thanks @jjguerrette.

2022-08-19 19:01 UTC, ibanos90 commented on config/jedi/ObsPlugs/variational/filtersWithBias/ahi_himawari8.yaml
> +  obs filters:
That's right. I will change it. Thanks @jjguerrette.

2022-08-19 19:07 UTC, jjguerrette approved these changes

2022-08-19 19:15 UTC, merged