Update base yamls stubs following IODA refactoring
NCAR/MPAS-Workflow pull request #157
Opened 2022-09-28 18:54 UTC by ibanos90

### Description
This PR updates all `ObsPlugs/*/base/*.yaml` stubs following the refactoring of IODA engines classes and parameters structures according to https://github.com/JCSDA-internal/ioda/pull/776 (adopted solution follows https://github.com/JCSDA-internal/mpas-jedi/pull/786). A new build of the mpas-bundle code is used to account for these modifications.

### Issue closed
Closes #154

### Tests completed
 - [ ] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [ ] 3dvar_OIE120km_ColdStart
 - [ ] 3dvar_O30kmIE60km_ColdStart
 - [ ] 3denvar_O30kmIE60km_WarmStart
 - [ ] eda_OIE120km_WarmStart

Complete set of tests is underway.

2022-09-28 20:57 UTC, jjguerrette requested changes
Only a few minor changes/comments.  Waiting for tests to be updated before approving.  Thank you for the quick turnaround @ibanos90.

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/hofx/base/aircraft.yaml
> -      max frame size: 40000
Do you mind putting a comment in the PR message that `max frame size` no longer works for `obsdataout`?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/hofx/base/iasi_metop-a.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/hofx/base/iasi_metop-b.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/hofx/base/iasi_metop-c.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/variational/base/iasi_metop-a.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/variational/base/iasi_metop-b.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 20:57 UTC, jjguerrette commented on config/jedi/ObsPlugs/variational/base/iasi_metop-c.yaml
>        max frame size: 80000
Does `max frame size` need to be removed here?

2022-09-28 21:05 UTC, ibanos90 commented
> Only a few minor changes/comments. Waiting for tests to be updated before approving. Thank you for the quick turnaround @ibanos90.

Thanks for your review @jjguerrette! I will remove the `max frame size` from those yamls.

2022-09-28 21:11 UTC, ibanos90 commented on config/jedi/ObsPlugs/hofx/base/aircraft.yaml
> -      max frame size: 40000
That's a good point. It would be good for future reference. Thanks.

2022-09-29 18:02 UTC, jjguerrette commented
Did the tests finish @ibanos?  I'm going to merge your branch into my departure sign change branch in order to run my own tests.

2022-09-29 19:42 UTC, ibanos90 commented
> Did the tests finish @ibanos? I'm going to merge your branch into my departure sign change branch in order to run my own tests.

Hi @jjguerrette! Most of the tests did, but I am getting an error in the tests with ColdStart:
```
Bad parameter: /: Mandatory parameter 'sensor' not found caught in  (/glade/p/mmm/parc/ivette/pandac/jedi/22SEP2022/mpas-bundle/oops/src/oops/runs/Run.cc +192 execute)
Exception: oops::Variational<MPAS, UFO and IODA observations> terminating...
Exception stack: 
Bad parameter: /: Mandatory parameter 'sensor' not found
backtrace [5] stack has 24 addresses
```
I am double checking the yaml files.

2022-09-29 23:23 UTC, ibanos90 commented
Hi @jjguerrette, all the tests now complete successfully after adding the `sensor` specification for the `ObsErrorFactorSurfJacobianRad` observations function.

2022-09-30 16:26 UTC, jjguerrette commented
> all the tests now complete successfully after adding the `sensor` specification for the `ObsErrorFactorSurfJacobianRad` observations function.

Just a formality, but please check the boxes before merging.

2022-09-30 16:26 UTC, jjguerrette approved these changes

2022-09-30 17:34 UTC, merged