Feature/4denvar derecho cylc8
NCAR/MPAS-Workflow pull request #268
Opened 2023-12-11 23:43 UTC by RGNystrom

### Description
Adding 4DEnVar functionality to our MPAS-JED-Workflow. Please let me know any issues with these proposed additions/changes and I am happy to take additional suggestions.

### Issue closed

Closes #205 

### Tests completed
#### Tier 1:
 - [ ] 3dvar_OIE120km_WarmStart
 - [ ] 3denvar_OIE120km_IAU_WarmStart
 - [ ] 3dvar_OIE120km_ColdStart
 - [ ] 3dvar_O30kmIE60km_ColdStart
 - [ ] 3denvar_O30kmIE60km_WarmStart
 - [ ] eda_OIE120km_WarmStart
 - [ ] getkf_OIE120km_WarmStart
 - [ ] ForecastFromGFSAnalysesMPT

#### Tier 2 (optional):
 - [ ] GenerateGFSAnalyses
 - [ ] GenerateObs

2023-12-11 23:58 UTC, liujake commented
@RGNystrom This PR includes also 'GOM' lines commented out in satellite yaml files, which is fine to me. But better to info this in the PR message.

2023-12-12 18:16 UTC, ibanos90 commented on initialize/applications/Forecast.py
> +      lengthHR = 9
We can make these variables configurable as they were before via yaml files

2023-12-12 18:19 UTC, ibanos90 commented on scenarios/defaults/variational.yaml
> +        #bumpLocDir: /glade/derecho/scratch/nystrom/pandac/60km.bumploc.duplicated.limited_derecho
This line can be removed?

2023-12-12 18:20 UTC, ibanos90 commented on tools/substituteEnsembleBTemplate.py
> +  #filename = args.directory0+'/'+'%iMember%/'+directory1+args.File
Same here

2023-12-12 18:21 UTC, ibanos90 commented on tools/substituteEnsembleBTemplate_4d_7slots.py
> +  #filename7 = args.directory0+'/'+'%iMember%/'+directory1+args.File7
Maybe we can delete these too

2023-12-12 18:22 UTC, jim-p-w commented on bin/InitEnKF.csh
>    rm ${TemplateFieldsFileOuter}${memSuffix}
rm templateFields.${nCellsOuter}.${thisMPASFileDate}.nc${memSuffix}

2023-12-12 18:22 UTC, jim-p-w commented on bin/InitVariationals.csh
> +  if ("$subwindow" == "1") then
consider using else if for subwindow == "1" and a final else with an error, e.g.
```
else if ("$subwindow" == "1") then
...
else
  echo "$0 (ERROR): invalid subwindow value:${subwindow} > ./FAIL
  exit 1
endif

2023-12-12 18:22 UTC, jim-p-w commented on bin/InitVariationals.csh
>    ln -sfv ${bgFileOther} ${bgFile}${OrigFileSuffix}
if `bgFileOther` resolves to multiple values at line 443, the link commands at lines 448 and 449 probably aren't what is desired?
Perhaps those link commands should be in an else clause after the if clause at line 451?

2023-12-12 18:22 UTC, jim-p-w commented on bin/InitVariationals.csh
>    rm ${TemplateFieldsFileOuter}${memSuffix}
rm templateFields.${nCellsOuter}.${thisMPASFileDate}.nc${memSuffix}

2023-12-12 18:27 UTC, ibanos90 commented on config/mpas/variational/streams.atmosphere_3d
It seems like the only difference between `streams.atmosphere`, `streams.atmosphere_3d`, and `streams.atmosphere_4denvar` is the value of the variable `filename_template`. Can we make that a variable that changes depending on the DA method or something like that? That way we do not need to replicate the streams file

2023-12-12 18:35 UTC, ibanos90 requested changes
Hi @RGNystrom, thanks for this PR. Given that lots of files are changed, can you provide more information in the description of the PR? It will be good for our later reference of the code. Also, can you add a small test to the reference tests so we make sure the 4denvar is regularly tested? A misc thing, I noted there are some blank spaces, can you please remove them (they appear as red when you do `git diff`)?

2023-12-12 20:19 UTC, RGNystrom commented on config/mpas/variational/streams.atmosphere_3d
Yes, only streams.atmosphere is needed. I forgot to remove the others. Thanks!

2023-12-12 20:26 UTC, mos3r3n commented on README.md
On derecho, the ~/.cylc/global.rc doesn't take effect because the cylc8 is used. The cylc8 needs to set ~/.cylc/flow/global.cylc file. Its content could be:
```
[platforms]
    [[pbs_cluster]]
        hosts = localhost
        job runner = pbs
        install target = localhost
```
It's a basic one, and more modifications could be done to it.

2023-12-12 20:27 UTC, jim-p-w commented on README.md
> -    work directory = /glade/scratch/USER/cylc-run
Cylc 8 uses a different config file. If you wish I will update the directions for cylc8/derecho in [PR 269](https://github.com/NCAR/MPAS-Workflow/pull/269)

2023-12-12 20:27 UTC, jim-p-w commented on scenarios/defaults/variational.yaml
> +          nodes: 448
Is this a typo? I haven't seen a request for this many nodes. I not, perhaps add a comment about why so many nodes are needed?

2023-12-12 20:48 UTC, RGNystrom commented on README.md
> -    work directory = /glade/scratch/USER/cylc-run
Yes, that sounds good

2023-12-12 20:49 UTC, RGNystrom commented on scenarios/defaults/variational.yaml
> +          nodes: 448
All of these actually need to be updated for all experimentson Derecho. I think this is best left to its own PR.

2023-12-13 16:21 UTC, ibanos90 approved these changes
@RGNystrom thanks for addressing all reviewers comments! All changes look good to me and reference tests are passing including the added for 4denvar. Can be merged once https://github.com/NCAR/MPAS-Workflow/pull/269 is merged

2023-12-13 16:39 UTC, jim-p-w commented on tools/substituteEnsembleBTemplate_4d.py
I have a question about the two new python apps, substituteEnsembleB_4d and substituteEnsembleB_4d_7slots.
It looks like substituteEnsembleB_4d_7slots is a superset  of substituteEnsembleB_4d and substituteEnsembleB.
Does it make sense to have just one app, and have it do the right thing based on, say, a command line switch?

2023-12-13 16:43 UTC, RGNystrom commented on tools/substituteEnsembleBTemplate_4d.py
One is for 4denvar with 3 subwindows and the other is for 7 subwindows. I think it is easiest to keep both for now, but we may be able to have one in the future.

2023-12-13 17:26 UTC, merged