Script to run cylc jobs and graph results.
NCAR/MPAS-Workflow pull request #329
Opened 2024-11-19 21:07 UTC by jim-p-w

### Description
This PR has a script which will run cylc jobs and graph the results.
It is intended to by run from cron, but can also be run manually.
Command line options control whether the script will run a cycl job, or look for results of previously started job.

Testing was done manually.

Note this relies on changes to the graphing code, including https://github.com/JCSDA-internal/mpas-jedi/pull/1022, plus changes which are dependent on PR 1022.

2025-02-11 00:12 UTC, amstokely requested changes

2025-02-11 00:12 UTC, amstokely commented on env-setup/run_cylc.sh
> +# get comamnd line args
I'm guessing you meant command :) .

2025-02-27 22:22 UTC, jim-p-w commented on env-setup/run_cylc.sh
> +# get comamnd line args
You guessed correctly! Typo fixed.

2025-03-10 17:41 UTC, amstokely approved these changes

2025-03-10 22:40 UTC, merged