Feature/FirstFC_coldstart
NCAR/MPAS-Workflow pull request #54
Opened 2021-12-08 22:40 UTC by ibanos90

This PR enables MPAS-Workflow to create cold start conditions from an external GFS analysis (cold start), in addition to using a pre-generated first forecast (warm start) and to reinitiate the cycling or the suite from any cycle (restart).

**Changes:**
A new variable "InitializationType" is defined in the config/experiment.csh script which can take values ColdStart/WarmStart/ReStart (note that ReStart is meant for the workflow when restarting from a cycle that had previously failed or stopped for any reason). In this PR is ensured that the initial cycle is the same for both initialization types, cold and warm start. In order to do that, several changes were needed in the config/modeldata.csh script in which the first date is used instead of using the previous one. The next date is also introduced.

In addition, part of the SetupWorkflow.csh script was moved to the "warmStart.csh" script, which is the one that creates the link/copy of the pre-generated first forecast. Other changes in SetupWorkflow.csh script were necessary to create the corresponding "CStart.csh" and "WStart.csh" scripts for each initialization type. The forecast.csh script was also modified to allow its use for the first forecast generation.

**Caveat**: 
The namelist.atmosphere for the generation of the first forecast only differs from the one used for warm start in that the variable "config_do_DAcycling" in the &restart block is equal false (otherwise is true). I tried to add this as a variable substitution but it did not work (left the intended changes commented out). Therefore, a new variable "NamelistFileIni" was added in the forecast.csh script and the namelist.atmosphere_Init file is added to account for the config_do_DAcycling = false.

Closes https://github.com/NCAR/MPAS-Workflow/issues/51

2021-12-08 22:45 UTC, ibanos90 commented
Tests conducted:

Cold start: 3denvar
Warm start: 3denvar and eda_3denvar 
VerifyDeterministicDA = True
Restart: from cycles 20180415T00 and 20180415T06 (after a cold or warm start run) to 20180415T12

2021-12-09 20:00 UTC, jjguerrette requested changes
Very good work!  Thank you Ivette.

No major revisions needed, though I have lots of small comments about renaming to fit my otherwise non-documented conventions of the repo and a few questions.  FYI, my general approach to naming variables is to make them verbose enough to understand in context.  Sometimes that means avoiding prefixes/suffixes that are already implied by the context, and sometimes that means providing lots of information in the variable, script, or cylc task name (e.g., `GetWarmStartIC`).

2021-12-09 20:00 UTC, jjguerrette commented on config/experiment.csh
> +setenv DAType 3denvar
Change back to eda_3denvar.  Remove 3dvar until we actually have it implemented.

2021-12-09 20:00 UTC, jjguerrette commented on config/experiment.csh
> +setenv LeaveOneOutEDA False
Change back to True

2021-12-09 20:00 UTC, jjguerrette commented on config/experiment.csh
> -
Add back line break

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> -
add back line break

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +#### another setting for the intialization type
Either clarify or remove comment

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +set VerifyEnsMeanBG = False
Change back to True

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +set DiagnoseEnsSpreadBG = False
Change back to True

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +source SetupWorkflow.csh
Why sourcing instead of executing?  Also, does this need to be executed all the time or only when `$initialCyclePoint == $firstCyclePoint`?

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +  set cyclingCycles = PT${CyclingWindowHR}H
Why do these need to be different?

2021-12-09 20:00 UTC, jjguerrette commented on SetupWorkflow.csh
> +chmod 744 ${JobScript}
Is there any difference between `CStart.csh` and `CyclingFC.csh`?  If not, then both cylc tasks can use the same csh script.

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +    env-script = cd ${mainScriptDir}; ./CStart.csh "1" "clStart"
Following up on my SetupWorkflow.csh comment, would replacing `CStart.csh` with `CyclingFC.csh` on line 373 yield the same result?  If so, there is no need to have two different scripts.

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +  [[CStart]]
Please change the name of the cylc task from `CStart` to `ColdStartFC`

2021-12-09 20:00 UTC, jjguerrette commented on drive.csh
> +  [[WStart]]
Please change the name of the cylc task and csh script names from `WStart` to `GetWarmStartIC`.  Then the new task that converts GRIB to mpas cold-start init files will be `GenerateColdStartIC`.

2021-12-09 20:00 UTC, jjguerrette commented on forecast.csh
> +if ( ${initType} == "clStart" ) then
Please change the `initType` strings as follows: `clStart` to `cold` and `wmStart` to `warm`

2021-12-09 20:00 UTC, jjguerrette commented on forecast.csh
> +#sed -i 's@DAcycling@'${do_DAcycling}'@' $NamelistFile
By default this changes the first instance of `DAcycling` in a line to whatever string is held by `$do_DAcycling`.  There are two instances of `DAcycling` on the same line in the namelist.  So all you need to do is pick a different substitution string, like `configDODACycling` instead of `DAcycling`.

2021-12-09 20:00 UTC, jjguerrette commented on config/modeldata.csh
> +setenv prevFirstCycleDate ${prevFirstCycleDate}
Do you mind reminding me where `prevFirstCycleDate` and `prevFirstFileDate` are still used?  I'm wondering if we can remove them.

2021-12-09 20:00 UTC, jjguerrette commented on SetupWorkflow.csh
> +echo `pwd`
Remove

2021-12-09 20:00 UTC, jjguerrette commented on SetupWorkflow.csh
> +cp warmStart.csh ${JobScript}
In combination with my comment in drive.csh and previous practice for SetupWorkflow.csh, `warmStart.csh` can simply be named `GetWarmStartIC.csh`.  Then you can remove lines 63-66 and add `GetWarmStartIC.csh` to the `workflowParts` list on line 17.

2021-12-09 20:05 UTC, jjguerrette commented
FYI @ibanos90, you can commit additional changes to this same branch then push them with `git push`.  The PR will update.

2021-12-13 21:39 UTC, ibanos90 commented on SetupWorkflow.csh
> +echo `pwd`
Removed

2021-12-13 21:39 UTC, ibanos90 commented on SetupWorkflow.csh
> +chmod 744 ${JobScript}
You are right, now both cylc tasks use the same csh script. Thanks for pointing this out!

2021-12-13 21:39 UTC, ibanos90 commented on SetupWorkflow.csh
> +cp warmStart.csh ${JobScript}
Sure! Done as recommended.

2021-12-13 21:39 UTC, ibanos90 commented on config/experiment.csh
> +setenv DAType 3denvar
Done as recommended.

2021-12-13 21:39 UTC, ibanos90 commented on config/experiment.csh
> +setenv LeaveOneOutEDA False
Changed

2021-12-13 21:39 UTC, ibanos90 commented on config/experiment.csh
> -
Added

2021-12-13 21:40 UTC, ibanos90 commented on config/modeldata.csh
> +setenv prevFirstCycleDate ${prevFirstCycleDate}
Sure! prevFirstCycleDate is still used in the PrepVariational.csh script line 369 for the variable "FirstCyclingFCDir". prevFirstFileDate is only set in config/modeldata.csh and I don't see its use in other scripts. I did a test and it can be removed.

2021-12-13 21:40 UTC, ibanos90 commented on drive.csh
> -
Added

2021-12-13 21:40 UTC, ibanos90 commented on drive.csh
> +#### another setting for the intialization type
Comment removed

2021-12-13 21:40 UTC, ibanos90 commented on drive.csh
> +set VerifyEnsMeanBG = False
Changed

2021-12-13 21:40 UTC, ibanos90 commented on drive.csh
> +set DiagnoseEnsSpreadBG = False
Changed

2021-12-13 21:40 UTC, ibanos90 commented on drive.csh
> +source SetupWorkflow.csh
You are right, it should be executed. After several attempts, the only way the suite was completely updated for the case of a restart initialization type was when the this script is executed and then all scripts were created again. However, I am not sure why it doesn’t work otherwise. The R1 task for the initial cycle point for the restart remained the same as in the warm start if this is not done.

2021-12-13 21:41 UTC, ibanos90 commented on drive.csh
> +  set cyclingCycles = PT${CyclingWindowHR}H
For a restart initialization type we may want to start just at the cycle that crashed or stopped for any reason, not 6h before. I can certainly think in other solution if you think the first cycle in a restart case should start 6h before. Please let me know what would be the best way to proceed.

2021-12-13 21:41 UTC, ibanos90 commented on drive.csh
> +  [[CStart]]
Changed

2021-12-13 21:41 UTC, ibanos90 commented on drive.csh
> +    env-script = cd ${mainScriptDir}; ./CStart.csh "1" "clStart"
Yes, it does the same and thus I modified it in the drive.csh script.

2021-12-13 21:41 UTC, ibanos90 commented on drive.csh
> +  [[WStart]]
Changed

2021-12-13 21:41 UTC, ibanos90 commented on forecast.csh
> +if ( ${initType} == "clStart" ) then
Changed

2021-12-13 21:42 UTC, ibanos90 commented on forecast.csh
> +#sed -i 's@DAcycling@'${do_DAcycling}'@' $NamelistFile
You are right. With this change the substitution is successful. Now we can use the same namelist file for both initialization types and just change the configDODACycling variable accordingly. Thank you!

2021-12-13 21:53 UTC, jjguerrette commented on config/modeldata.csh
> +setenv prevFirstCycleDate ${prevFirstCycleDate}
Thanks!

2021-12-13 21:54 UTC, ibanos90 commented
> 

Thanks @jjguerrette! I did a new commit with all the changes you recommended. I think I covered all of them, but please let me know if I left something out. I run the same tests as before and everything is working well.

2021-12-13 21:55 UTC, jjguerrette commented on drive.csh
> +  set cyclingCycles = PT${CyclingWindowHR}H
You make a good justification.  Do you mind adding comments in the two different branches of the if clause describing that reasoning?  Then we will be reminded how to set the first cycle date and initial cycle point appropriately .

2021-12-13 21:57 UTC, jjguerrette commented on forecast.csh
> +## arg to get the initialization type
Please add a comment describing valid values for this argument (`cold`, `warm`).  See experiment.csh for similar examples.

2021-12-13 22:01 UTC, jjguerrette commented
Thank you @ibanos90 for the changes.  It looks very good, and I added only a few requests for in-line comments.  Looking at the "Files changed" tab on the github page, there is a very small footprint from this PR, which is a great example of how to add new functionality while minimally impacting existing functionality.  I will run some tests too.

2021-12-13 23:00 UTC, ibanos90 commented on drive.csh
> +  set cyclingCycles = PT${CyclingWindowHR}H
Sure! Thanks for that suggestion. I added some comments.

2021-12-13 23:00 UTC, ibanos90 commented on forecast.csh
> +## arg to get the initialization type
Added some comments

2021-12-13 23:02 UTC, ibanos90 commented
Thanks @jjguerrette! I added some in-line comments as suggested in the recent commit.

2021-12-14 17:01 UTC, jjguerrette commented on drive.csh
> +      '''
You have explained this to me multiple times, but I'm still trying to understand why this branch of the if statement is necessary.  It seems like the `cyclingCycles` variable ought to handle all situations without an R1 task for `ReStart`.

2021-12-14 19:26 UTC, jjguerrette commented on drive.csh
> +  # The cycles will run every 6h, starting 6h after the initial cycle point
Maybe replace `6h` with `CyclingWindowHR` or "`CyclingWindowHR` hours"?

2021-12-14 19:27 UTC, jjguerrette commented on drive.csh
> +#      '''
As discussed in person, delete lines 214-217

2021-12-14 19:27 UTC, jjguerrette commented on getCycleVars.csh
> -
Add this line break back

2021-12-14 20:29 UTC, ibanos90 commented on drive.csh
> +  # The cycles will run every 6h, starting 6h after the initial cycle point
Replaced it with "CyclingWindowHR hours"

2021-12-14 20:30 UTC, ibanos90 commented on drive.csh
> +#      '''
Lines deleted

2021-12-14 20:30 UTC, ibanos90 commented on getCycleVars.csh
> -
Added

2021-12-14 20:32 UTC, ibanos90 commented
Thanks for all the suggestions @jjguerrette! I ran the same tests as before and all seems working ok.

2021-12-14 21:22 UTC, jjguerrette commented on drive.csh
> +#                   (run after a warm start cycle that crashed or stopped for any reason)
Would the following changes be accurate for this comment?
```
#          restart: restart the cycling/suite from any cycle 
#            run from a warm start forecast produced from an already existing workflow, which could
#            have been originally initiated from either a warm or cold start initial condition
```

2021-12-14 21:23 UTC, ibanos90 commented on drive.csh
> +#                   (run after a warm start cycle that crashed or stopped for any reason)
Yes, this looks much better!

2021-12-14 21:25 UTC, jjguerrette commented on forecast.csh
> +#       warm: same as InitializationType = WarmStart in config/experiment.csh
These comments should be independent of settings in other scripts.  The descriptions need to be in the context of running a forecast, not in the context of the whole workflow.  For example,
```
#       cold: initial condition is produced from MPAS's init executable (i.e., core_init_atmosphere)
#       warm: initial condition is an output state from a previous MPAS forecast (i.e., core_atmosphere)
```

2021-12-14 21:26 UTC, jjguerrette commented on getCycleVars.csh
> +
No need to add a space at the beginning of the line.

2021-12-14 21:27 UTC, jjguerrette commented on getCycleVars.csh
> +
FYI, these kinds of small formatting changes will show up with `git diff develop`.  It's very useful for eliminating spacing changes.

2021-12-14 21:36 UTC, ibanos90 commented on forecast.csh
> +#       warm: same as InitializationType = WarmStart in config/experiment.csh
Thanks for pointing this out! I used your example of comment.

2021-12-14 21:36 UTC, ibanos90 commented on getCycleVars.csh
> +
Ok. I deleted the space

2021-12-14 21:37 UTC, jjguerrette commented on forecast.csh
> +#       warm: same as InitializationType = WarmStart in config/experiment.csh
I realize now that my previous advice on writing these comments was vague.

2021-12-14 21:45 UTC, ibanos90 commented on getCycleVars.csh
> +
You are right, I forgot to do the diff with the develop branch before committing the changes. Thanks!

2021-12-14 22:43 UTC, jjguerrette commented on drive.csh
>  # + CyclingFC must have been completed for the cycle before initialCyclePoint. Set > FirstCycleDate to automatically restart#   from a previously completed cycle.
This old comment is not exactly accurate any more.  I will pull this branch to test and also fix this comment.

2021-12-14 23:04 UTC, ibanos90 commented on drive.csh
>  # + CyclingFC must have been completed for the cycle before initialCyclePoint. Set > FirstCycleDate to automatically restart#   from a previously completed cycle.
That's right. Thank you!

2021-12-14 23:05 UTC, jjguerrette commented on forecast.csh
> +  set initialState = ${localStaticFieldsFile}
I see that in your next feature branch this `localStaticFieldsFile` usage gets replaced.  So I will wait to see where you go in the next steps.  That was my final comment.  Running tests now.

2021-12-14 23:12 UTC, ibanos90 commented on forecast.csh
> +  set initialState = ${localStaticFieldsFile}
Yes, it will be replaced by the cold start initial condition created with mpas_init. Thank you for all of your comments!

2021-12-15 01:13 UTC, jjguerrette commented
I made a few small nuanced changes.  I tested the 3denvar cold-start, 3denvar warm-start, and eda_3denvar warm-start for 3 cycles.  I also restarted from the second cycle of the 3denvar cold- and warm-starts.

2021-12-15 01:25 UTC, jjguerrette approved these changes
Thank you for the hard work!  Feel free to check over my last commit.  Merge when you are ready.

2021-12-15 06:33 UTC, ibanos90 commented
Thanks for the changes in the last commit @jjguerrette!

2021-12-15 06:36 UTC, merged