Feature/Ungrib_GFSana
NCAR/MPAS-Workflow pull request #59
Opened 2022-01-04 21:03 UTC by ibanos90

This PR enables the use of WPS ungrib to decode the GFS analysis in grib format to generate the cold start initial conditions for the MPAS model forecast. GFS analysis on RDA archives on Cheyenne are used instead of pre-downloaded and ungribbed GFS analyses. This allows to run experiments for any date available on RDA archive. Nevertheless, this is still only working for the data period of the pre-generated data since we are using 3denvar and it needs the ensemble forecasts for the covariance matrix. With the implementation of 3dvar in the future, we can then run experiments for any date.

**Changes**:
- The UngribColdStartIC.csh script was created to ungrib the GFS analysis using the ungrib executable. The corresponding namelist was added to the folder config/mpas/init;
- The static data files specification in config/modeldata.csh was moved to the scripts ColdStartModelData.csh and WarmStartModelData.csh in order to specify the data source according to the initialization type;
- The if statement for the initialization type in the forecast.csh script was modified in order to specify the correct initial state when using cold start for the first date or any other date. The option to update the sea ice was added in this statement (this may change with the surfaces generation)

**Caveats**:
For now, the sea ice is not updated in this application. It will be implemented in the near future.

Closes https://github.com/NCAR/MPAS-Workflow/issues/53

2022-01-04 22:05 UTC, jjguerrette requested changes
Pretty close to ready.  Only a few minor changes.

2022-01-04 22:05 UTC, jjguerrette commented on getCycleVars.csh
> +endif
Since the same value persists for all cycles, `StaticFieldsDirOuter` and `StaticFieldsDirInner` can be set in `config/modeldata.csh` when `${InitializationType} == "ColdStart"`.  `getCycleVars.csh` is used for setting variables that differ in each cycle.

`GFSAnaDirVerify` on line 102 needs to use `GFSAnaDirOuter` instead of `GFSAnaDirEnsemble`.  Additionally, the only place that `GFSAnaDirVerify` is used is in `verifymodel.csh`.  `thisValidDate` is used therein to determine the appropriate date.  So I think line 102 may need to be removed OR modified then moved to `config/modeldata.csh`.

2022-01-04 22:05 UTC, jjguerrette commented on forecast.csh
> +  set updateSea = 0
This all looks good for now.  Do you expect that the only change will be to set `updateSea` to 1 on line 79 once that functionality is enabled?

2022-01-04 22:05 UTC, jjguerrette commented on config/ReStartModelData.csh
> +WarmStartModelData.csh
This will be a problem if we ever wish to restart a workflow initiated from a ColdStart forecast. I think the only two relevant values of `InitializationType` are `ColdStart` and `WarmStart`.  It can be determined if this is a restart simply by comparing the `initialCyclePoint` and `FirstCycleDate`.  That affects the R1 task...probably something like below.  You had a blank `else` clause there before, but I asked you to delete it.  My mistake.  Except I do not think there needs to be a `ReStart` `InitializationType`.

```
{% if initialCyclePoint == FirstCycleDate %} #might need to modify to get both dates in the same format
  {% if InitializationType == "ColdStart" %}
      [[[R1]]]
        graph = GenerateColdStartIC => ColdStartFC => CyclingFCFinished
  {% elif InitializationType == "WarmStart" %}
      [[[R1]]]
        graph = GetWarmStartIC => CyclingFCFinished
  {% endif %}
{% endif %}
```

2022-01-04 22:05 UTC, jjguerrette commented on getCycleVars.csh
> +source config/${InitializationType}ModelData.csh
If this is actually required, probably `config/experiment.csh` ought to be source first.  Maybe with the changes suggested below the `*ModelData` will not be needed.

2022-01-12 08:51 UTC, ibanos90 commented on getCycleVars.csh
> +endif
You are right. I moved the if statement when ${InitializationType} == "ColdStart" to config/modeldata.csh. In addition, I moved all the data source specifications back to config/modeldata.csh. Please let me know if it looks good like this.

In the case of GFSAnaDirVerify, I changed it to use GFSAnaDirOuter for WarmStart but kept it as GFSAnaDirEnsemble for ColdStart in order to use the GFS analyses already in ${EnsembleModelData}. In the future we can move this variable to verifymodel.csh in order to use the valid date

2022-01-12 08:51 UTC, ibanos90 commented on forecast.csh
> +  set updateSea = 0
So far I think that would be the main change

2022-01-12 08:52 UTC, ibanos90 commented on config/ReStartModelData.csh
> +WarmStartModelData.csh
I agree that we should only have ColdStart and WarmStart initialization types, thus I removed the ReStart type. Following your suggestion I modified drive.csh and now the R1 tasks and cylc cycling cycles depend on the dates

2022-01-12 08:54 UTC, ibanos90 commented on getCycleVars.csh
> +source config/${InitializationType}ModelData.csh
After moving all the data source specifications back to config/modeldata.csh, sourcing this file is in fact not longer needed

2022-01-12 19:29 UTC, jjguerrette commented on config/modeldata.csh
> +  setenv GFSAnaDirVerify ${GFSAnaDirEnsemble}
I am under the impression that `GFSAnaDirVerify` should always be equal to `GFSAnaDirOuter` in fully functioning WarmStart or ColdStart situations.  Is this a holdover until the ColdStart automatically generates the `GFSAnaDirOuter` data on the fly?  If so, please add a comment to that effect.  If I am mistaken, do you mind explaining?

2022-01-12 19:32 UTC, jjguerrette commented on forecast.csh
> +  set updateSea = 0
Please add a comment on this line, something like the following.

```
  TODO(IHB): enable sea surface updating for ColdStart and set updateSea to 1 below
```

This is a useful indicator for the reviewer to know that some work will be done in a follow-up PR.

2022-01-12 20:48 UTC, ibanos90 commented on forecast.csh
> +  set updateSea = 0
This is a good point. I added the suggested line to this script

2022-01-12 20:48 UTC, ibanos90 commented on config/modeldata.csh
> +  setenv GFSAnaDirVerify ${GFSAnaDirEnsemble}
Yes, you are right. This is holdover until the GFS analyses from RDA are ungribbed and mpas_init executed each cycle for verification purposes. Then, GFSAnaDirVerify will be equal to GFSAnaDirOuter for both initialization types. As suggested, I added a comment to the script

2022-01-12 20:53 UTC, jjguerrette commented on config/builds.csh
> +setenv ungribBuildDir /glade/work/guerrett/pandac/data/GEFS
What do you think about using the ungrib.exe and link_ungrib.csh from the directory below?

```
/glade/u/home/wrfhelp/PRE_COMPILED_CODE/WPSV4.0_intel_serial_large-file/
```

2022-01-12 20:55 UTC, jjguerrette commented on config/modeldata.csh
> +setenv linkWPSdir /glade/scratch/mpasrt/wps
Since link_grib.csh is an executable script that is packaged with the WPS source code, probably good to co-locate the `linkWPSdir` with `ungribBuildDir`.  Maybe even rename both of them to WPSBuildDir.

2022-01-12 20:59 UTC, ibanos90 commented on config/builds.csh
> +setenv ungribBuildDir /glade/work/guerrett/pandac/data/GEFS
Sure! I will test it to make sure it works well

2022-01-12 21:00 UTC, ibanos90 commented on config/modeldata.csh
> +setenv linkWPSdir /glade/scratch/mpasrt/wps
That makes sense. I will make these changes and commit the changes

2022-01-12 21:02 UTC, jjguerrette commented on drive.csh
> +# + CyclingFC must have been completed for the cycle before initialCyclePoint. Set > FirstCycleDate to automatically restart#   from a previously completed cycle.
Re-insert line break before
```
#   from a previously completed cycle.
```

2022-01-12 21:02 UTC, jjguerrette commented on drive.csh
> +
Looks good.  Nice and simple.

2022-01-12 21:02 UTC, jjguerrette commented on forecast.csh
> +else if ( ${InitializationType} == "ColdStart" & ${thisValidDate} != ${FirstCycleDate}) then
I'm not totally sure about the difference between bitwise and logical and (`&` vs. `&&` according to https://www2.cs.duke.edu/csl/docs/unix_course/intro-130.html), but usually I use the latter.

So maybe change `&` to `&&`.

2022-01-12 21:28 UTC, ibanos90 commented on config/builds.csh
> +setenv ungribBuildDir /glade/work/guerrett/pandac/data/GEFS
The executable from that directory gives the following error:
`./ungrib.exe: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory`
I remember I got this error before while trying to use a different executable than the one in /glade/work/guerrett/pandac/data/GEFS

2022-01-12 21:33 UTC, jjguerrette commented on config/builds.csh
> +setenv ungribBuildDir /glade/work/guerrett/pandac/data/GEFS
OK, we can use the one I built for now.  Probably we need to load specific modules for th PRE_COMPILED_CODE.  Thanks for trying.

2022-01-12 21:35 UTC, jjguerrette commented on config/modeldata.csh
> +setenv linkWPSdir /glade/scratch/mpasrt/wps
Based on the PRE_COMPILED_CODE, it is OK for the two directories to be different for now.  Perhaps when you move `linkWPSdir` to config/builds.csh, could you add a TODO to remind us to eventually get those from the same build?

2022-01-12 22:00 UTC, ibanos90 commented on config/modeldata.csh
> +setenv linkWPSdir /glade/scratch/mpasrt/wps
There is a link_grib.csh script in /glade/work/guerrett/pandac/data/GEFS which I can use for now. Then, the same directory can be used for both the link_grib.csh script and the ungrib executable.

2022-01-12 22:09 UTC, ibanos90 commented on drive.csh
> +# + CyclingFC must have been completed for the cycle before initialCyclePoint. Set > FirstCycleDate to automatically restart#   from a previously completed cycle.
Line break re-inserted

2022-01-12 22:10 UTC, ibanos90 commented on forecast.csh
> +else if ( ${InitializationType} == "ColdStart" & ${thisValidDate} != ${FirstCycleDate}) then
Changed & to && in lines 67 and 72

2022-01-12 22:16 UTC, jjguerrette commented on getCycleVars.csh
> +set InitICDir = (${InitICWorkDir}/${thisCycleDate})
Why is `InitICDir` moved back to getCycleVars.csh?  It is only used in forecast.csh when `${thisValidDate} == ${FirstCycleDate}`.  So there will always be a specific date associated with it.

2022-01-12 22:51 UTC, ibanos90 commented on getCycleVars.csh
> +set InitICDir = (${InitICWorkDir}/${thisCycleDate})
I needed to include the date to InitICDir because in config/modeldata.csh it was equal to only ${GFSAnaDirOuter}.
I changed it as it was before but I am adding `setenv InitICDir ${InitICWorkDir}/${FirstCycleDate}` in config/modeldata.csh in order to create the directory with the date associated for the initial conditions. In the future it needs to be modified in order to create the initial conditions for each cycle. Does that makes sense?

2022-01-12 22:55 UTC, jjguerrette commented on getCycleVars.csh
> +set InitICDir = (${InitICWorkDir}/${thisCycleDate})
It makes sense that `${GFSAnaDirOuter}/${thisCycleDate}` would be used at multiple cycles to create the initial conditions at each cycle for verification.  Moving "${InitICWorkDir}/${FirstCycleDate} in config/modeldata.csh" as you propose in the above comment is all I was suggesting.  Again, if there are steps to be completed in a follow-on PR, it's helpful to make note of them with a TODO.

2022-01-12 23:05 UTC, jjguerrette reviewed
One final comment.  Feel free to address in a follow-on PR.  Great work!

After the passing test list is added to the PR description, I'm ready to approve.  Let me know if I can help run some tests.

Hopefully cold/warm and first/restart dates have been tested for 120km.

2022-01-12 23:05 UTC, jjguerrette commented on forecast.csh
>  endif
It looks like the only difference between these two `else if` branches is the `updateSea` value.  Other code is the same and duplication could be removed.

2022-01-12 23:06 UTC, ibanos90 commented on getCycleVars.csh
> +set InitICDir = (${InitICWorkDir}/${thisCycleDate})
Thanks! I added a comment

2022-01-12 23:42 UTC, ibanos90 commented on forecast.csh
>  endif
You are right. I made some changes and moved updateSea back to config/modeldata.csh

2022-01-13 00:10 UTC, jjguerrette commented on forecast.csh
>  endif
Thanks

2022-01-13 03:29 UTC, ibanos90 commented
> 

I added the list of tests conducted to the PR description. Thanks for your review!

2022-01-13 16:04 UTC, jjguerrette approved these changes
Thanks you.  Before merging, please update the title to something related to the work being completed by this PR.

2022-01-13 16:26 UTC, merged