Add observation preprocessing from RDA
NCAR/MPAS-Workflow pull request #63
Opened 2022-02-04 09:40 UTC by ibanos90

**Description**:
This PR adds the preprocessing of RDA archived NCEP BUFR observations to IODA-v2 format and their assimilation into the workflow. Jamie's obs2ioda converter (https://github.com/jamiebresch/obs2ioda) is used to convert prepbufr, satwnd, satwind, and 1bamua (default observations in the list provided for now, others can be uncommented and converted as well) observations and then the ioda-upgrade.x executable is used to get the correct string station_id and string variable_names of the preburf observations. This allows to run experiments for any date using the ColdStart initialization type and it can also be used for WarmStart cases. The preprocessing of the observations listed as default takes around 2 minutes of walltime. The walltime increases as more observations as added but still is less than 10 minutes even with IASI observations.

**Changes**:
- A new script based on rda_obs2ioda.csh (Jamie's script) was added to convert the observations to IODA-v2 and the folder with the new observations is located in the experiment run directory. 
- Adjusts were made in PrepJEDI.csh to account for the proper data source taking into account if the option to preprocess the observations is on/off.

**Test**:
- Various tests were conducted:
 Cold Start and the new converted observations for different dates ==> OIE120km, 3dvar 
 WarmStart using pre-generated observations and the new converted observations ==> OIE120km, 3dvar, 3denvar
 
**Caveats**:
- The model space verification still is not working for other dates because of the need to generate the GFS analysis for each cycle for the new dates. This will be subject of future developments.

Closes https://github.com/NCAR/MPAS-Workflow/issues/56

2022-02-04 17:41 UTC, jjguerrette requested changes
Only a few minor changes requested.  Looks great overall!

2022-02-04 17:41 UTC, jjguerrette commented on ObstoIODA.csh
> +#source config/obsdata.csh
This commented line can be removed.

2022-02-04 17:41 UTC, jjguerrette commented on ObstoIODA.csh
> +source config/modeldata.csh
What is needed from modeldata.csh?

2022-02-04 17:41 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +- obs space:
If sfc.yaml replaces sfcp.yaml, then usually I would use a `git mv` to change the file name and maintain the git history of the file.  In any case, the `sfcp.yaml` files can be removed _if_ they are now obsolete.  Same for the variational version.

FYI, I just looked in the diagnostic python scripts.  We already use `sfc` instead of `sfcp` there.  So surface pressure diagnostics should work with this change.

2022-02-04 17:41 UTC, jjguerrette commented on ObstoIODA.csh
> +        echo "Source file: ${RDAdataDir}/ds351.0/bufr/${ccyy}/${THIS_FILE}"
Where is `RDAdataDir` defined?

2022-02-04 17:41 UTC, jjguerrette commented on config/experiment.csh
> +set obtypes = ($l)
Do you mind using a more informative name than `obtypes`?  Maybe `preprocessObsList` or something similar?

2022-02-04 17:41 UTC, jjguerrette commented on config/mpas/O30kmIE120km/job.csh
> +setenv ObstoIODAMemory 109
I'm seeing that my original design of setting job resource requirements uniquely for each `GridDescriptor` is forcing you to copy the same settings in multiple places.  In a follow-on PR, we ought to define mesh-independent job resource requirements in a single place.  This also applies to VerifyObs* resources.

Nothing to change in this PR.

2022-02-04 17:41 UTC, jjguerrette commented on drive.csh
> +{% set obtypes = "${obtypes}" %}
Again, something more informative than `obstypes` would be preferred.

2022-02-04 17:41 UTC, jjguerrette commented on PrepJEDI.csh
> +if ( $ArgPrepObsOn == True ) then
At some point in the future I would prefer that we move this kind of `if` statement to the configuration level to avoid PrepJEDI.csh needing to know where observations are located in these two unique situations.  That being said, this solution works just fine for our first two use-cases.

2022-02-04 19:47 UTC, ibanos90 commented on ObstoIODA.csh
> +source config/modeldata.csh
In modeldata.csh we define the variable RDAdataDir which corresponds to the directory were all RDA data is on Cheyenne. This was done in first place because of the script UngribColdStartIC.csh that needs the RDA GFS forecasts. Should we define this variable in other script?

2022-02-04 19:48 UTC, ibanos90 commented on PrepJEDI.csh
> +if ( $ArgPrepObsOn == True ) then
Yes, I agree. I think it would be great if all the observations for the different use-cases were under the same folder (variable name), then the specifications could be handled in obsdata.csh for example.

2022-02-04 19:48 UTC, ibanos90 commented on config/mpas/O30kmIE120km/job.csh
> +setenv ObstoIODAMemory 109
I agree. We can put all the same job specifications in a single place.

2022-02-04 19:50 UTC, ibanos90 commented on ObstoIODA.csh
> +        echo "Source file: ${RDAdataDir}/ds351.0/bufr/${ccyy}/${THIS_FILE}"
In modeldata.csh. This follows up the previous question.

2022-02-04 20:44 UTC, ibanos90 commented on ObstoIODA.csh
> +#source config/obsdata.csh
Removed in the last commit

2022-02-04 20:45 UTC, ibanos90 commented on config/ObsPlugs/hofx/sfc.yaml
> +- obs space:
You are right, I forgot to rename the files. It was updated in the last commit

2022-02-04 20:45 UTC, ibanos90 commented on config/experiment.csh
> +set obtypes = ($l)
Sure. I used the suggested name in the last commit

2022-02-04 20:45 UTC, ibanos90 commented on drive.csh
> +{% set obtypes = "${obtypes}" %}
Changed as well.

2022-02-07 16:07 UTC, jjguerrette commented on ObstoIODA.csh
> +source config/modeldata.csh
Thank you for the reminder!  I forgot that you already added other RDA data usage.

2022-02-07 16:12 UTC, jjguerrette commented on config/environmentIODAupgrade.csh
> +setenv GFORTRAN_CONVERT_UNIT 'big_endian:101-200'
Maybe these settings could be defined in a file named `environmentForJedi.csh`, then sourced in `config/environment.csh`.  No need to repeat it twice in two files.

2022-02-07 16:15 UTC, jjguerrette commented on drive.csh
> +  {% endif %}
The commented line 174 can be uncommented and this if statement simplified as follows.
```
{% set PrimaryCPGraph = PrimaryCPGraph + "\\n        CyclingFCFinished[-PT${CyclingWindowHR}H]" %}
{% if PreprocessObs == "True" %}
  {% set PrimaryCPGraph = PrimaryCPGraph + " => ObstoIODA" %}
{% endif %}
```

2022-02-07 18:01 UTC, ibanos90 commented on config/environmentIODAupgrade.csh
> +setenv GFORTRAN_CONVERT_UNIT 'big_endian:101-200'
You are right. I made the suggested changes.

2022-02-07 18:01 UTC, ibanos90 commented on drive.csh
> +  {% endif %}
Thanks for pointing this out and the recommended change!

2022-02-07 18:11 UTC, jjguerrette commented on ObstoIODA.csh
> +  source ${mainScriptDir}/config/environment.csh
I recall that you mentioned there was a need to load the the environment without NCO or python in order for the upgrader to work.  Is this supposed to be `environmentForJEDI` instead of `environment`?  If not and only one environment is needed, no need to have two different files.  Maybe we can discuss offline.

If environmentForJEDI needs to exist, then I would think that `${BuildCompiler}` would be derived by sourcing  `config/builds.csh` within `environmentForJEDI.csh` similar to how it is used now in `environment.csh`.  Then the duplication between the two environment scripts would be removed.

2022-02-07 19:33 UTC, ibanos90 commented on ObstoIODA.csh
> +  source ${mainScriptDir}/config/environment.csh
Honestly, I am not sure why the upgrader does not work with just `environment.csh` since it contains most of the modules needed. I tried merging both and changing the position of the modules loaded but nothing worked. So, for now, we do need to source `environmentForJEDI.csh` in `ObstoIODA.csh`. I did as you suggested to avoid duplication in the scripts and added a work around to pass `BuildCompiler` as an argument into `environmentForJEDI.csh`. This is because we need to source `environmentForJEDI.csh` inside the Observations folder (`${WorkDir}`). I am not sure if this would the best solution though.

2022-02-07 19:37 UTC, jjguerrette commented on config/environmentForJedi.csh
> +
Very nice solution.  Do you mind giving documentation of the argument (similar to other command-line arguments in the workflow), including possible options here?

So far the only possible values are
`gnu-openmpi`
`intel-impi`

2022-02-07 20:27 UTC, ibanos90 commented on config/environmentForJedi.csh
> +
Sure. I added a comment for the argument passed and used the same variable name `BuildCompiler`. However, this is also documented in builds.csh. Is it ok to keep both documentation of the argument? Or should I change the variable name?

2022-02-07 21:22 UTC, jjguerrette commented on config/environmentForJedi.csh
> +
It's fine.  The alternative would be to source `config/builds.csh` within `config/environmentForJEDI.csh`.  Up to you.  Let me know when you are satisfied and I will approve.

2022-02-07 21:50 UTC, ibanos90 commented on config/environmentForJedi.csh
> +
I agree. The problem with sourcing `config/builds.csh` within `config/environmentForJEDI.csh` is that it needs the whole path to the `config` folder and for that other files need to also be sourced. Then, I thought of adding the argument to simplify. If you think is good for now you can approve it. In the future we can move these changes back once we don't need to run the upgrader for prebufr data.

2022-02-07 21:53 UTC, jjguerrette commented on config/environmentForJedi.csh
> +
Sure.  We'll see what is needed when we have time to revisit.  It's good to get you moving forward.  GNSSRO still in a separate PR?

2022-02-07 21:53 UTC, jjguerrette approved these changes

2022-02-07 21:55 UTC, jjguerrette requested changes

2022-02-07 21:55 UTC, jjguerrette commented on ObstoIODA.csh
> +source config/experiment.csh
Since config/experiment.csh is sourced, I think the OBSTYPES argument is redundant.

2022-02-07 21:56 UTC, jjguerrette commented on drive.csh
> +{% set preprocessObsList = "${preprocessObsList}" %}
Thus, this line can be removed as well.

2022-02-07 21:59 UTC, ibanos90 commented on ObstoIODA.csh
> +source config/experiment.csh
You are right. I will remove the argument. Thanks for catching that!

2022-02-07 21:59 UTC, ibanos90 commented on drive.csh
> +{% set preprocessObsList = "${preprocessObsList}" %}
Sure. Thank you!

2022-02-07 22:09 UTC, jjguerrette commented on ObstoIODA.csh
> +source config/experiment.csh
Then lines 6-10 can be removed entirely, right?

2022-02-07 22:21 UTC, jjguerrette approved these changes

2022-02-07 22:22 UTC, ibanos90 commented on ObstoIODA.csh
> +source config/experiment.csh
Yes, sorry I thought I had deleted them.

2022-02-07 22:33 UTC, merged