Extensions to QC flags in YAML stubs for conventional and AMSU-A observations
NCAR/MPAS-Workflow pull request #70
Opened 2022-02-22 19:36 UTC by ibanos90

### Description
This PR adds extensions to quality control flags in YAML stubs for conventional and amsua observations from NOAA-15, 18, and 19, Aqua, and Metop-A and B satellites. The filters used are based on Junmei's newest code: `/glade/scratch/jban/pandac/testpr_220126/DA/2018041500/3denvar.yaml`. Observation errors for amsua observations are already provided in the observations files as part of the conversion from BURF to IODA-v2 using Jamie's converter. A Gaussian thinning filter is added for the variational data assimilation in which the thinning distance is 200km for the 120km mesh and 145km for finer meshes. A new variable is added to `config/experiment.csh` to indicate the source of the satellite bias coefficients that are needed for the amsua bias correction. All related satellite bias configuration is moved to `satbiasdata.csh`. 
 
### Issue closed
Closes https://github.com/NCAR/MPAS-Workflow/issues/43

### Tests completed
 - WarmStart
   - [x] OIE120km 3dvar, 2 cycles
   - [x] OIE120km 3denvar, 2 cycles
   - [x] OIE120km eda_3denvar, 2 cycles
   - [x] O30kmIE60km 3denvar, 2 cycles
 - ColdStart
   - [x] OIE120km 3dvar, 2 cycles, PreprocessObs=True, Satbias=GDASFixed

2022-02-22 20:32 UTC, jjguerrette commented
Thank you for submitting the PR @ibanos90.  This will take me a while to review as there are a lot of intricate file changes.  I will look through it a little today to see if there is any high-level feedback I can provide.  Our detailed discussion will have to wait until after you return.

2022-02-22 21:24 UTC, ibanos90 commented
> Thank you for submitting the PR @ibanos90. This will take me a while to review as there are a lot of intricate file changes. I will look through it a little today to see if there is any high-level feedback I can provide. Our detailed discussion will have to wait until after you return.

Sounds good. Thanks @jjguerrette.

2022-02-23 21:02 UTC, jjguerrette requested changes
Took a first pass at the QC settings.  Probably will need to look again after fixes.  Will review other files soon.

As a question, I wonder if setting the anchor for `Sensor_ID` in multiple places causes any problems.  It is possible that only the first instance of that anchor will be respected.  I would suggest removing those shorthands.  I believe that an anchor name is only supposed to be defined once in a yaml file to avoid ambiguity, but could be wrong.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/aircraft.yaml
> +    threshold: 3
Delete

- `apply at iterations` is not applicable to HofX
- We do not want Background Check filters to be applied during HofX, because it changes the observations that are selected between experiments, and invalidates the comparison between multiple experiments.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_aqua.yaml
> +  - filter: Background Check
Same comment for `Background Check` in HofX.  Remove.  Same across all amsua and conventional instruments.  Keep the `Background Check` filter in place for the variational yamls though.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_metop-a.yaml
> +  - filter: Background Check
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_aqua.yaml
> +#   passedBenchmark: 1472
Remove all lines in all yamls that have `passedBenchmark`.  These are only used in UFO testing and are irrelevant to MPAS-Workflow.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_metop-b.yaml
> +  - filter: Background Check
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_n15.yaml
> +  - filter: Background Check
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_n18.yaml
> +  - filter: Background Check
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_n19.yaml
> +  - filter: Background Check
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/gnssroref.yaml
> +    threshold: 3.0
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwind.yaml
> +    apply at iterations: 0, 1
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwind.yaml
> +    obs perturbations seed: 1
Remove `obs perturbations seed`, irrelevant for HofX

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwind.yaml
> +#    horizontal_mesh: RADTHINDISTANCE #km
Remove commented thinning filters.  We can add it back at a later time if we decide it is needed.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwnd.yaml
> +    apply at iterations: 0, 1
Remove Background Check

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwnd.yaml
> +    obs perturbations seed: 1
Remove `obs perturbations seed`

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +    obs perturbations seed: 1
Remove

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/satwind.yaml
> +    obs perturbations seed: 1
Remove.

This is handled in `config/ObsPlugs/variational/ObsAnchors.yaml` with the `ObsSpace` anchor.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/satwnd.yaml
> +    obs perturbations seed: 1
Remove.

This is handled in `config/ObsPlugs/variational/ObsAnchors.yaml` with the `ObsSpace` anchor.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/sfc.yaml
> +    obs perturbations seed: 1
Remove.

This is handled in `config/ObsPlugs/variational/ObsAnchors.yaml` with the `ObsSpace` anchor.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/sondes.yaml
> +    apply at iterations: 0
Remove, PreQC only needs to be done once.  The flags are static across outer iterations.  The default value for `apply at iterations` in OOPS is `0`.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/satwind.yaml
>    obs error: *ObsErrorDiagonal
Is any more QC needed for `satwind`?  Or does PreQC do most of the work?

I would expect `satwnd` and `satwind` to have similar kinds of filters, including some kind of ObsError assignment.

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/satwnd.yaml
> +  - filter: BlackList
Please change all instances of `BlackList` to `Perform Action` (in all yamls) when they include an `action` key.    For example, when `action: reject`, `action: inflate error`, or `action: assign error` are present.

The behavior is equivalent between the two filters and the `Perform Action` name is more informative.

FYI, in a very much related sense, there is a general push in software engineering to move away from terms like "black list", "dummy variable", "master", "slave", and other similarly exclusionary terms. There is an initiative at UCAR to do that as well, which is another motivating factor.

E.g.,
https://www.marketplace.org/2020/06/17/tech-companies-update-language-to-avoid-offensive-terms/
https://www.drupal.org/node/2286193
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/
https://www.zdnet.com/article/mysql-drops-master-slave-and-blacklist-whitelist-terminology/
https://www.pcmag.com/news/apple-to-remove-masterslave-and-blacklist-terms-from-coding-platforms

2022-02-23 21:02 UTC, jjguerrette commented on config/ObsPlugs/variational/gnssroref.yaml
> -      maxvalue: 30000.0
Please do not modify these values by removing the `.0`.  Same for all YAMLS where a floating point number is changed in this PR to look like an integer.

2022-02-25 16:15 UTC, jamiebresch commented on ObstoIODA.csh
>  setenv SPC_COEFF_DIR /glade/u/home/hclin/proj/ioda/SpcCoeff
Not related to this PR. Just a note that these two settings should be relocated to a common pandac directory.
This obs_errtable is linked to a table used by Craig in some of his experiments.
The SpcCoeff for converting IR radiances is the same as in CRTMTABLES directory.

2022-03-03 20:42 UTC, jjguerrette commented
Note that I just merged develop in order to resolve conflicts that I created in #71.  There were only 3 conflicts. One of them I resolved by adding back `config/ObsPlugs/hofx/sondes-2018043006.yaml`.  If that file was purposefully removed and there is a plan to handle the case for missing specific_humidity, please remove the yaml stub again.

2022-03-03 21:35 UTC, jjguerrette commented
I also created a version of this branch called `merge/QCflags_YAMLS/autotest_cases`, which includes a quasi-clean merge of `feature/autotest_cases`.  I did not test it yet, but it is probably a better starting point than `feature/QCflags_YAMLS` since it utilizes all of the auto-testing features and YAML configuration methods.

I added a lot of in-line comments in `merge/QCflags_YAMLS/autotest_cases`, especially with regard to the satellite bias correction.
1. The main point is that we need to be able to turn off bias correction completely in order to run sensitivity tests for new instruments.  In order to keep using the `PANDACArchive` data (which is pre-bias-corrected), we would like `None` to be the default bias correction setting and not `GDASFixed`.  I understand that will make the YAML settings difficult to set up, so let's talk about it when you return.  Possibly we can add a directory like `config/ObsPlugs/biasCorrect` that includes the yaml stubs with the `obs bias` section of each instrument.

2. In this PR, please only add the bias correction to the `Variational` application (`PrepVariational` instead of `PrepJEDI`).  If we want to turn on bias correction for `HofX` later, we can shift your working components around as needed.

2022-03-15 14:39 UTC, ibanos90 commented on ObstoIODA.csh
>  setenv SPC_COEFF_DIR /glade/u/home/hclin/proj/ioda/SpcCoeff
@jamiebresch Thanks for pointing this out!

2022-03-15 14:52 UTC, ibanos90 commented
> I also created a version of this branch called `merge/QCflags_YAMLS/autotest_cases`, which includes a quasi-clean merge of `feature/autotest_cases`. I did not test it yet, but it is probably a better starting point than `feature/QCflags_YAMLS` since it utilizes all of the auto-testing features and YAML configuration methods.
> 
> I added a lot of in-line comments in `merge/QCflags_YAMLS/autotest_cases`, especially with regard to the satellite bias correction.
> 
>     1. The main point is that we need to be able to turn off bias correction completely in order to run sensitivity tests for new instruments.  In order to keep using the `PANDACArchive` data (which is pre-bias-corrected), we would like `None` to be the default bias correction setting and not `GDASFixed`.  I understand that will make the YAML settings difficult to set up, so let's talk about it when you return.  Possibly we can add a directory like `config/ObsPlugs/biasCorrect` that includes the yaml stubs with the `obs bias` section of each instrument.
> 
>     2. In this PR, please only add the bias correction to the `Variational` application (`PrepVariational` instead of `PrepJEDI`).  If we want to turn on bias correction for `HofX` later, we can shift your working components around as needed.

Thanks @jjguerrette for the review and creating a version of this branch with the recent changes of the develop branch. That was very helpful! 
I am just wondering if the bias correction coefficients needed for the satellite data assimilation should be added in `PrepVariational` or keep it in `PrepJEDI` since in `PrepJEDI` is where the yaml substitution related to the observations takes place.
I will close this PR for now, but changes based on the suggested modifications and comments will be submitted in a following PR.

2022-03-15 14:52 UTC, closed without merging