Feature/real time
NCAR/MPAS-Workflow pull request #78
Opened 2022-03-18 05:30 UTC by ibanos90

### Description
This PR extends current capabilities in the MPAS-Workflow to enable the execution of a near-real-time system using data from the NCEP FTP (last 10 days) as well as retrospective experiments using RDA data on Cheyenne. This functionality is available for 3DVar data assimilation with a 120-km single-resolution mesh, assimilating prepburf (aircraft, sondes, surface, and satwind), satwnd, and gnssro (refractivity) observations and using GFS analysis for cold start initial conditions for any date. It also enables the model verification against GFS analysis at each cycle. QC flags in yamls for aircraft, sondes, surface, satwind, satwnd and gnssro are based on Junmei's newest code: /glade/scratch/jban/pandac/testpr_220126/DA/2018041500/3denvar.yaml. Following Junmei's guidance, surface observations (from prepbufr) are converted to IODA-v2 format using the "noqc" flag which indicates that no additional QC are applied. A RealTime scenario was added to run recent dates with the specific configuration. This is an initial prototype of a near-real-time application upon which many other functionalities can be added as needed.

### Tests completed
 - [x] 3dvar_OIE120km_WarmStart
 - [x] 3denvar_OIE120km_WarmStart
 - [x] 3dvar_OIE120km_ColdStart
 - [x] 3denvar_O30kmIE60km_WarmStart
 - [x] eda_OIE120km_WarmStart
 - [x] RealTime => 2 days completed so far without crashing and running up to now. The most recent cycle (2022031718) was executed at 01:03 UTC (19:03 MDT), 20 minutes after all observations files were available (at 00:43 UTC was made available the prepbufr file).

2022-03-18 18:29 UTC, jjguerrette requested changes
Wow, that was a lot of work @ibanos90!!!

Mostly cosmetic requests.

2022-03-18 18:29 UTC, jjguerrette commented on GetGFSanalysis.csh
> +    # otherwise, retry until available
`otherwise, retry until available` --> `otherwise, exit with failure`

The decision to retry is outside this script and the script itself need not know about it.

2022-03-18 18:29 UTC, jjguerrette commented on GetGFSanalysis.csh
> +     echo "$gfs_file not available yet -- waiting"
`-- waiting` --> `-- exiting`

2022-03-18 18:29 UTC, jjguerrette commented on GetNCEPFTPobs.csh
> +    # otherwise, retry until available
Same comment

2022-03-18 18:29 UTC, jjguerrette commented on GetNCEPFTPobs.csh
> +     echo "$ftp_file not available yet -- waiting"
Same comment

2022-03-18 18:29 UTC, jjguerrette commented on GetRDAobs.csh
> +# Copy and untar CISL RDA archived NCEP BUFR files based on Jamie Bresch (NCAR/MMM) script rda_obs2ioda.csh
It would be better for us to have an acknowledgement or contributor section in the README than to credit particular scripts to contributors.  This repository need not know about a particular script name outside of the repo.

2022-03-18 18:29 UTC, jjguerrette commented on GetRDAobs.csh
> +source config/obsdata.csh
Is obsdata still needed?  Can probably remove.  Same in other scripts.

2022-03-18 18:29 UTC, jjguerrette commented on GetRDAobs.csh
> +source config/${InitializationType}ModelData.csh
Why does `GetRDAobs` depend on the `${InitializationType}ModelData.csh`?  If it does, we need to (1) move that variable out of model data or (2) make a copy specifically in `observations.csh` or locally here.  Observations and model source information need not depend on one another.

2022-03-18 18:29 UTC, jjguerrette commented on GetRDAobs.csh
> +  if ( ${inst} == satwnd ) then
This is a lot of if clauses.  I would like to see them documented more carefully, because we likely will not understand them all in 2 months or whenever we come back to it.  Either as part of this PR or a follow-on issue (add to a list of follow-on tasks).

2022-03-18 18:29 UTC, jjguerrette commented on ObsToIODA.csh
> +source config/obsdata.csh
Is obsdata.csh needed anymore?

2022-03-18 18:29 UTC, jjguerrette commented on ObsToIODA.csh
> +setenv PREPBUFRflag "-noqc"
`PREPBUFRflag` --> `noGSIQCFilters`

2022-03-18 18:29 UTC, jjguerrette commented on config/ColdStartModelData.csh
> +setenv updateSea 0
Please put a `TODO` here to turn on sea-surface updating (future PR).  Add to follow-on task list.

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/hofx/amsua_metop-a.yaml
> +      Sensor_ID: amsua_metop-a
Wow, nice catch!  Oops

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/hofx/satwind.yaml
> +#    horizontal_mesh: RADTHINDISTANCE #km
Based on Jake's comment in the PANDA-C meeting, I think we need to start deflating the ObsError and turn on thinning for `satwind`.  Would be good to get info from @junmeiban.

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +    name: Identity
Remove.  No linear obs operator in `HofX`.

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +    <<: *multiIterationFilter
Remove.  For now `multiIterationFilter` is not defined in `hofx/ObsAnchors.yaml`.  So this alias may cause an error.

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/variational/satwnd.yaml
> +    <<: *multiIterationFilter
Please move the `Background Check` after the `Perform Action` filter that assigns the error.  This ensures that we use the final error setting.  The `Background Check` is usually preferred to be the last filter after all others have run.

2022-03-18 18:29 UTC, jjguerrette commented on config/ObsPlugs/variational/satwnd.yaml
> +  - filter: Perform action
Does this work ~~is~~ as `Perform action`?  It might be case sensitive and really needs to be `Perform Action` (see L112 of `ufo/src/ufo/instantiateObsFilterFactory.h`.  Same elsewhere that `Perform action` is specified.

2022-03-18 18:29 UTC, jjguerrette commented on config/model.csh
> +$setNestedModel AnaSource
`AnaSource` --> `AnalysisSource`

Let's be verbose.

2022-03-18 18:29 UTC, jjguerrette commented on config/modeldata.csh
> +source config/${InitializationType}ModelData.csh
Can the `source` be moved to the top of the script with the others?

2022-03-18 18:29 UTC, jjguerrette commented on config/mpas/OIE120km/job.csh
> +setenv VerifyModelPEPerNode 36
The `Verify*` node and PE settings are no longer used in `drive.csh` and can be deleted.  Is the extra time (5 min. instead of 2 min.) needed for sure?

2022-03-18 18:29 UTC, jjguerrette commented on config/mpas/OIE30km/job.csh
> +source config/workflow.csh
Nice catch!

2022-03-18 18:29 UTC, jjguerrette commented on GetRDAobs.csh
> +  else
For my own learning, does this branch of the if statement handle `gpsro` too?

2022-03-18 18:29 UTC, jjguerrette commented on ObsToIODA.csh
> +  set types = ( aircraft ascat profiler satwind sfc sondes satwnd )
Does `gpsro` or `gnssro` need to be added here?

2022-03-18 18:29 UTC, jjguerrette commented on drive.csh
> +      execution retry delays = ${NCEPftpRetry}
Please specify the `execution time limit`.

2022-03-18 18:29 UTC, jjguerrette commented on drive.csh
> +      execution retry delays = ${GFSAnalysisRetry}
Please specify the `execution time limit`.

2022-03-18 18:29 UTC, jjguerrette commented on getCycleVars.csh
> +set CyclingDADirs = (${CyclingDAWorkDir}/${thisCycleDate})
I might have messed this up in the merge.  L15 is repeated again on L19.  L15 can be deleted.

2022-03-18 18:29 UTC, jjguerrette commented on scenarios/RealTime.yaml
> +  nInnerIterations: [15,]
The real-time workflow can use 60 inner iterations for now.  We may increase outer iterations later.

2022-03-18 18:29 UTC, jjguerrette commented on scenarios/RealTime.yaml
> +  CPQueueName: economy
`CPQueueName` can be `premium`.  We want these jobs to get through the queue fast.

2022-03-18 18:29 UTC, jjguerrette commented on scenarios/base/model.yaml
> +# OPTIONS: PANDACGFSArchive, GFSRDAOnline, GFSNCEPFTPOnline
These names need to be standardized: PANDACGFSArchive, GFSRDAOnline, GFSNCEPFTPOnline

Maybe something like below?

GFSfromPANDACArchive
GFSfromRDAOnline
GFSfromNCEPFTPOnline

2022-03-18 18:36 UTC, jjguerrette commented
We also need to change the name of `satwindBufr` to `satwnd` in `mpas-jedi/graphics/config.py` in order to enable the diagnostics.  @ibanos, can you submit a companion PR to mpas-jedi with a branch that has the same name?  Should only be a single-line change:
https://github.com/JCSDA-internal/mpas-jedi/blob/ecf7e632f601139e3a3773ca10d1b4af67cff0bd/graphics/config.py#L329

2022-03-18 21:21 UTC, ibanos90 commented on GetGFSanalysis.csh
> +    # otherwise, retry until available
Done.

2022-03-18 21:21 UTC, ibanos90 commented on GetGFSanalysis.csh
> +     echo "$gfs_file not available yet -- waiting"
Done.

2022-03-18 21:21 UTC, ibanos90 commented on GetNCEPFTPobs.csh
> +    # otherwise, retry until available
Done.

2022-03-18 21:21 UTC, ibanos90 commented on GetNCEPFTPobs.csh
> +     echo "$ftp_file not available yet -- waiting"
Done.

2022-03-18 21:21 UTC, ibanos90 commented on GetRDAobs.csh
> +# Copy and untar CISL RDA archived NCEP BUFR files based on Jamie Bresch (NCAR/MMM) script rda_obs2ioda.csh
I added an Acknowledgements section in the Readme.md, but please let me know if you have any other inputs on this.

2022-03-18 21:21 UTC, ibanos90 commented on GetRDAobs.csh
> +source config/obsdata.csh
You are right. I removed it from this script and others.

2022-03-18 21:22 UTC, ibanos90 commented on GetRDAobs.csh
> +source config/${InitializationType}ModelData.csh
Actually, I added the sourcing of ${InitializationType}ModelData.csh because the script `getCycleVars.csh` needs the variable `GFSAnaDirOuter` when `${InitializationType} == "ColdStart"`. As recommended, I removed this line from this script and the others, but added the same line in `getCycleVars.csh` in order to get the needed variable.

2022-03-18 21:22 UTC, ibanos90 commented on GetRDAobs.csh
> +  if ( ${inst} == satwnd ) then
Added some comments. Please take a look and let me know if more are needed.

2022-03-18 21:22 UTC, ibanos90 commented on ObsToIODA.csh
> +source config/obsdata.csh
Here we need the `CRTMTABLES` directory which is defined in obsdata.csh at this moment.

2022-03-18 21:22 UTC, ibanos90 commented on ObsToIODA.csh
> +setenv PREPBUFRflag "-noqc"
Changed.

2022-03-18 21:22 UTC, ibanos90 commented on config/ColdStartModelData.csh
> +setenv updateSea 0
Added.

2022-03-18 21:22 UTC, ibanos90 commented on config/ObsPlugs/hofx/amsua_metop-a.yaml
> +      Sensor_ID: amsua_metop-a
Thanks!

2022-03-18 21:22 UTC, ibanos90 commented on config/ObsPlugs/hofx/satwind.yaml
> +#    horizontal_mesh: RADTHINDISTANCE #km
I sent email to @junmeiban to get this info.

2022-03-18 21:22 UTC, ibanos90 commented on config/ObsPlugs/hofx/sfc.yaml
> +    name: Identity
Removed.

2022-03-18 21:23 UTC, ibanos90 commented on config/ObsPlugs/hofx/sfc.yaml
> +    <<: *multiIterationFilter
I actually forgot to add that variable in `hofx/ObsAnchors.yaml`. I added it now instead of removing the line from the yaml. Would that be ok?

2022-03-18 21:23 UTC, ibanos90 commented on config/ObsPlugs/variational/satwnd.yaml
> +    <<: *multiIterationFilter
Moved it in all yaml files.

2022-03-18 21:23 UTC, ibanos90 commented on config/ObsPlugs/variational/satwnd.yaml
> +  - filter: Perform action
Thanks for pointing this typo out.

2022-03-18 21:23 UTC, ibanos90 commented on config/model.csh
> +$setNestedModel AnaSource
Changed.

2022-03-18 21:23 UTC, ibanos90 commented on config/modeldata.csh
> +source config/${InitializationType}ModelData.csh
Yes, after the last changes I made we can move this upper. Thanks for catching this.

2022-03-18 21:23 UTC, ibanos90 commented on config/mpas/OIE120km/job.csh
> +setenv VerifyModelPEPerNode 36
I was not sure if those variable were needed anymore so I left them. Now I removed them as suggested.
I increased the time to 5 minutes because sometimes this task was failing. Will run more tests to be sure.

2022-03-18 21:23 UTC, ibanos90 commented on config/mpas/OIE30km/job.csh
> +source config/workflow.csh
Thanks!

2022-03-18 21:23 UTC, ibanos90 commented on GetRDAobs.csh
> +  else
Yes. gpsro follows the same name definition as other satellite data, so the following lines will be applicable:
L 62: `setenv THIS_FILE gdas.${inst}.t${hh}z.${ccyy}${mmdd}.bufr`
L 67: `set THIS_TAR_FILE = ${defaultBUFRDirectory}/${inst}/${ccyy}/${inst}.${ccyy}${mmdd}.tar.gz`

2022-03-18 21:24 UTC, ibanos90 commented on ObsToIODA.csh
> +  set types = ( aircraft ascat profiler satwind sfc sondes satwnd )
My understanding is that this is only needed for conventional observations (according to Jamie's comment [https://github.com/JCSDA-internal/ioda/issues/567#issuecomment-1016590401](url)). I checked this with Junmei and this step is not needed for gpsro data.

2022-03-18 21:24 UTC, ibanos90 commented on drive.csh
> +      execution retry delays = ${NCEPftpRetry}
Specified.

2022-03-18 21:24 UTC, ibanos90 commented on drive.csh
> +      execution retry delays = ${GFSAnalysisRetry}
Specified.

2022-03-18 21:24 UTC, ibanos90 commented on getCycleVars.csh
> +set CyclingDADirs = (${CyclingDAWorkDir}/${thisCycleDate})
Deleted.

2022-03-18 21:24 UTC, ibanos90 commented on scenarios/RealTime.yaml
> +  nInnerIterations: [15,]
Changed it to 60 inner iterations as suggested.

2022-03-18 21:24 UTC, ibanos90 commented on scenarios/RealTime.yaml
> +  CPQueueName: economy
Modified.

2022-03-18 21:24 UTC, ibanos90 commented on scenarios/base/model.yaml
> +# OPTIONS: PANDACGFSArchive, GFSRDAOnline, GFSNCEPFTPOnline
Changed the names and in other scripts as needed.

2022-03-18 22:29 UTC, ibanos90 commented
> We also need to change the name of `satwindBufr` to `satwnd` in `mpas-jedi/graphics/config.py` in order to enable the diagnostics. @ibanos, can you submit a companion PR to mpas-jedi with a branch that has the same name? Should only be a single-line change: https://github.com/JCSDA-internal/mpas-jedi/blob/ecf7e632f601139e3a3773ca10d1b4af67cff0bd/graphics/config.py#L329

Hi @jjguerrette! How would you suggest that I do that? From a forked repository or I can create a new feature branch and open the pull request as I do to MPAS-Workflow? Thank you!

2022-03-18 23:17 UTC, jjguerrette commented on README.md
> +- Junmei Ban (NCAR/MMM @junmeiban) for the guidance with the quality control flags in yaml stubs and satellite bias correction implementation.
Probably all contributors from our group can be listed as co-authors (Junmei, BJ, Jake, Yonggang, Ivette, JJ, Chris) in alphabetical order by last name.  We will need to flush out the acknowledgements section later as many people/teams deserve to be included.

2022-03-18 23:42 UTC, ibanos90 commented on README.md
> +- Junmei Ban (NCAR/MMM @junmeiban) for the guidance with the quality control flags in yaml stubs and satellite bias correction implementation.
Just to make sure I understood, do you mean to add a section of co-authors to the Readme?

2022-03-18 23:45 UTC, jjguerrette commented on GetRDAobs.csh
> +  if ( ${inst} == satwnd ) then
One comment for each "if" please.  That includes the entire chain of if's, i.e., L72-L111.

2022-03-18 23:45 UTC, jjguerrette commented on GetRDAobs.csh
> +     if ( -e ${GDASObsErrtable} ) then
If `${GDASObsErrtable}` does not exist, this should throw an error.  That would cause a deviation from our expected behavior.

2022-03-18 23:45 UTC, jjguerrette commented on ObsToIODA.csh
> +source config/obsdata.csh
Please either add to the follow-up list or do it now: move CRTMTABLES definition to observations.csh and observations.yaml, then remove this `source`.

2022-03-18 23:45 UTC, jjguerrette commented on config/ColdStartModelData.csh
> +setenv updateSea 0
Maybe more descriptive in terms of why the capability cannot be turned on.
```
# TODO: enable sea-surface file generation, then turn on sea-surface updating
```

2022-03-18 23:45 UTC, jjguerrette commented on config/ObsPlugs/hofx/ObsAnchors.yaml
> +  apply at iterations: 0,1,2,3,4,5
Thanks for adding.  There are no iterations in HofX.  This should be changed to 
```
_multi iteration filter: &multiIterationFilter
  _blank: null
```

2022-03-18 23:45 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +    <<: *multiIterationFilter
OK.  See comment in ObsAnchors.  Fine to keep `multiIterationFilter` here, with a caveat.  One thing I have as a long term goal is to use the same YAML stubs for hofx and variational (merge them), then anything that differs between them would be controlled by the workflow (e.g., background check, iteration-related, obs perturbations, MemberDir, etc.).  So including `multiIterationFilter` here aligns with that goal as long as the correct setting is in `ObsAnchors.yaml`.

2022-03-18 23:46 UTC, jjguerrette commented on README.md
> +- Junmei Ban (NCAR/MMM @junmeiban) for the guidance with the quality control flags in yaml stubs and satellite bias correction implementation.
Nevermind for this PR.  Let's open an issue that includes your acknowledgement for Jamie.  Then we will add the co-authors and acknowledgements in a separate PR.

2022-03-18 23:47 UTC, jjguerrette commented on GetRDAobs.csh
> +source config/${InitializationType}ModelData.csh
Does `GetRDAobs.csh` depend on `GFSAnaDirOuter`?  It should not.

2022-03-18 23:50 UTC, jjguerrette commented on config/mpas/OIE120km/job.csh
> +setenv VerifyModelPEPerNode 36
Fine to increase if it is necessary.  Maybe add an extra 1 min. compared to the longest run-time you see.

2022-03-18 23:52 UTC, jjguerrette commented
> > We also need to change the name of `satwindBufr` to `satwnd` in `mpas-jedi/graphics/config.py` in order to enable the diagnostics. @ibanos, can you submit a companion PR to mpas-jedi with a branch that has the same name? Should only be a single-line change: https://github.com/JCSDA-internal/mpas-jedi/blob/ecf7e632f601139e3a3773ca10d1b4af67cff0bd/graphics/config.py#L329
> 
> Hi @jjguerrette! How would you suggest that I do that? From a forked repository or I can create a new feature branch and open the pull request as I do to MPAS-Workflow? Thank you!

Yes, the same procedure as you follow for MPAS-Workflow.  Clone the repo (through mpas-bundle build if you already have one);  Pull the latest develop;  Create a new branch based off of develop; etc...

2022-03-19 00:13 UTC, ibanos90 commented on README.md
> +- Junmei Ban (NCAR/MMM @junmeiban) for the guidance with the quality control flags in yaml stubs and satellite bias correction implementation.
Ok. I opened the issue https://github.com/NCAR/MPAS-Workflow/issues/80 to address that.

2022-03-19 00:17 UTC, ibanos90 commented on GetRDAobs.csh
> +source config/${InitializationType}ModelData.csh
No, it does not.

2022-03-19 01:13 UTC, ibanos90 commented on ObsToIODA.csh
> +source config/obsdata.csh
I moved CRTMTABLES to observations.csh. The other variables in obsdata.csh were moved to variational.csh and the file was deleted from the repository.

2022-03-19 01:40 UTC, ibanos90 commented on config/mpas/OIE120km/job.csh
> +setenv VerifyModelPEPerNode 36
I ran several tests again and all tasks completed successfully within the 2 minutes, so I kept it like that. Thanks for this comment.

2022-03-19 01:45 UTC, ibanos90 commented on GetRDAobs.csh
> +  if ( ${inst} == satwnd ) then
Added more in-line comments. Please let me know if more are needed.

2022-03-19 01:46 UTC, ibanos90 commented on ObsToIODA.csh
> +source config/obsdata.csh
I moved CRTMTABLES to observations.csh. The other variables in obsdata.csh were moved to variational.csh and the file was deleted from the repository.

2022-03-19 01:47 UTC, ibanos90 commented on config/ColdStartModelData.csh
> +setenv updateSea 0
Added your suggested text

2022-03-19 01:49 UTC, ibanos90 commented on config/ObsPlugs/hofx/satwind.yaml
> +#    horizontal_mesh: RADTHINDISTANCE #km
Following Jake's guidance, I added the thinning of satellite winds (both satwind in prepburf and satwnd data) with a 145km of distance for all meshes for now. The same obs error deflation is equally applied to both satwnd and satwind, as recommended.

2022-03-19 01:52 UTC, ibanos90 commented on config/ObsPlugs/hofx/ObsAnchors.yaml
> +  apply at iterations: 0,1,2,3,4,5
Changed it. Sorry, I didn't realize there are no iterations for Hofx. Thanks!

2022-03-19 01:53 UTC, ibanos90 commented
> > > We also need to change the name of `satwindBufr` to `satwnd` in `mpas-jedi/graphics/config.py` in order to enable the diagnostics. @ibanos, can you submit a companion PR to mpas-jedi with a branch that has the same name? Should only be a single-line change: https://github.com/JCSDA-internal/mpas-jedi/blob/ecf7e632f601139e3a3773ca10d1b4af67cff0bd/graphics/config.py#L329
> > 
> > 
> > Hi @jjguerrette! How would you suggest that I do that? From a forked repository or I can create a new feature branch and open the pull request as I do to MPAS-Workflow? Thank you!
> 
> Yes, the same procedure as you follow for MPAS-Workflow. Clone the repo (through mpas-bundle build if you already have one); Pull the latest develop; Create a new branch based off of develop; etc...

Ok, will do it soon. Thanks!

2022-03-19 01:55 UTC, ibanos90 commented on GetRDAobs.csh
> +     if ( -e ${GDASObsErrtable} ) then
You are right. I added an `else` to throw an error if the table does not exist. Thanks for pointing this out.

2022-03-21 16:34 UTC, ibanos90 commented on ObsToIODA.csh
> +source config/obsdata.csh
I added CRTMTABLES definition to observations.csh and observations.yaml.

2022-03-21 17:15 UTC, jjguerrette commented on config/ObsPlugs/hofx/sfc.yaml
> +    <<: *multiIterationFilter
Remove L22.

This `Difference Check` does not need the `multiIterationFilter` alias.  The filter will remove all data in the first iteration that are going to be removed.  Re-running in subsequent outer iterations (for variational) would have no impact and add computational cost.

2022-03-21 17:23 UTC, jjguerrette commented on config/variational.csh
> +$setLocal InterpolationType
I think that `InterpolationType` fits better in `observations.yaml` because it similarly applies to HofX.  However, it will be irrelevant after the `GetValues` refactoring is merged.  Then we can remove `InterpolationType` altogether.  No need to change anything in this PR for now, because it would be time wasted.

2022-03-21 17:26 UTC, jjguerrette commented on drive.csh
> +    {% set PrimaryCPGraph = PrimaryCPGraph + " => GetNCEPFTPobs => ObsToIODA" %}
I wonder if the distinction between `GetRDAobs` and `GetNCEPFTPobs` could be controlled internally in a script called `GetObs` in a similar way that `GetGFSanalysis` internally distinguishes between RDA and FTP?  Then `drive.csh` does not need to decide which one to use.

2022-03-21 17:41 UTC, jjguerrette commented on PrepJEDI.csh
> +source config/variational.csh
I guess the need for `source config/variational.csh` is dictated by the `InterpolationType` config element.  We do NOT want to source `config/variational.csh` in `PrepJEDI.csh` for the `HofX` application.  So maybe we do want `InterpolationType` to be moved to `observations.yaml` after all.

2022-03-21 17:43 UTC, jjguerrette commented on PrepJEDI.csh
> +source config/variational.csh
Similarly, the VARBC substitution part can be moved to `PrepVariational.csh`, even though it does not do anything currently.  Originally I was not asking for the total removal of `obsdata.csh` in this PR.  Since you are most of the way there already, let's go all the way?

2022-03-21 17:47 UTC, ibanos90 commented on PrepJEDI.csh
> +source config/variational.csh
In one of my last commits I removed obsdata.csh completely and moved the variables definitions to either observations.yaml or variational.yaml.

2022-03-21 18:07 UTC, jjguerrette commented on PrepJEDI.csh
> +source config/variational.csh
I can meet to discuss this afternoon if you are available.  We only want PrepJEDI to depend on variational.yaml for Variational applications, not HofX applications.

2022-03-21 18:12 UTC, ibanos90 commented on PrepJEDI.csh
> +source config/variational.csh
As you suggested, I moved the `InterpolationType` definition to `observations.yaml `and `observations.csh`. I also deleted the sourcing of `variational.csh` from `PrepJEDI.csh`. I am not sure if this is what you were recommending. I am available this afternoon. Please let me know what hour works best for you.

2022-03-21 18:13 UTC, ibanos90 commented on config/variational.csh
> +$setLocal InterpolationType
I moved `InterpolationType` to `observations.yaml` as recommended

2022-03-21 18:14 UTC, jjguerrette commented on PrepJEDI.csh
> +source config/variational.csh
Yes, that is what I was asking.

2022-03-21 18:27 UTC, ibanos90 commented on config/ObsPlugs/hofx/sfc.yaml
> +    <<: *multiIterationFilter
This line was removed

2022-03-21 18:47 UTC, ibanos90 commented on drive.csh
> +    {% set PrimaryCPGraph = PrimaryCPGraph + " => GetNCEPFTPobs => ObsToIODA" %}
This is a good idea. I am working on it. Thanks for the suggestion!

2022-03-21 20:28 UTC, ibanos90 commented on drive.csh
> +    {% set PrimaryCPGraph = PrimaryCPGraph + " => GetNCEPFTPobs => ObsToIODA" %}
As suggested, `GetObs.csh `was added to control from where to get the observations according to the `resource`. Some changes were made in drive.csh to account for this modification.

2022-03-21 20:39 UTC, ibanos90 commented
Ran all suggested tasks with the latest changes and all completed successfully.

2022-03-21 21:24 UTC, jjguerrette commented on drive.csh
> +  {% if InitializationType == "ColdStart" %}
I like the consolidation of the obs processing to using the `InitializationType` instead of `observations__resource`.  In order for this to be user-safe though, whenever `InitializationType == "ColdStart"` we also need to either (1) force `observations__resource` to be equal to one of the `ColdStart`-compatible options (`GladeRDAOnline` or `NCEPFTPOnline`) in `observations.csh` or (2) emit an error with message when the user selects `observations__resource` to be `PANDACArchive`.  Probably it is OK to have `NCEPFTPOnline` as the default when `InitializationType == "ColdStart"`.  Let's assume somebody who wants to run a `ColdStart` scenario knows what they are doing.

2022-03-21 21:25 UTC, jjguerrette commented on drive.csh
> +  {% if InitializationType == "ColdStart" %}
Another possibility is to make the default option for `observations__resource` in scenarios/base/observations.yaml `None`.  Then all scenarios would need to specify a reasonable value.  I like that approach best I think.

2022-03-21 21:27 UTC, jjguerrette commented
I think this is ready to merge after we iron out my last comment.

2022-03-21 21:38 UTC, ibanos90 commented on drive.csh
> +  {% if InitializationType == "ColdStart" %}
I agree, I think the last approach is best. I will do that and submit changes.

2022-03-21 23:03 UTC, jjguerrette commented on drive.csh
> +  {% if InitializationType == "ColdStart" %}
I'm back on the fence about whether `InitializationType` should control whether this observation mini-workflow is executed.  I think we can address it in the follow-on work when we improve the observation processing dependencies (i.e., not depending on the previous forecast).

2022-03-21 23:04 UTC, jjguerrette approved these changes
Approve, assuming that all tests still pass.  Please merge along with MPAS-JEDI PR.  I need to update my local version of the diagnostic scripts to use `satwnd`.

2022-03-21 23:06 UTC, ibanos90 commented
Yes, I ran tests and all completed successfully. Thanks for the review, @jjguerrette!

2022-03-21 23:07 UTC, ibanos90 commented on drive.csh
> +  {% if InitializationType == "ColdStart" %}
Ok. I put this in the follow up tasks.

2022-03-21 23:08 UTC, merged

2022-03-21 23:41 UTC, jjguerrette commented
FYI @ibanos90, you may delete the branch after it is merged into `develop` using the button on the website.  Same comment for all your other PR's.  We have a record of the changes in the PR and merged commit.